name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - package: gcc-10
            CC: gcc-10
          - package: gcc-11
            CC: gcc-11
          - package: gcc-12
            CC: gcc-12
          - package: clang-13
            CC: clang-13
          - package: clang-14
            CC: clang-14
          - package: clang-15
            CC: clang-15
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y pkg-config valgrind meson ninja-build ${{ matrix.compiler.package }}
    - name: Test
      run: |
        env CC=${{ matrix.compiler.CC }}  meson setup build
        meson test --wrap='valgrind --leak-check=full --show-leak-kinds=all --verbose' -C build -v --timeout-multiplier 0
