name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y pkg-config gcc-10 valgrind clang-tools meson ninja-build
    - name: Test
      run: |
        meson setup build
        meson test --wrap='valgrind --leak-check=full --show-leak-kinds=all --verbose' -C build -v --timeout-multiplier 0
